[
uuid(3bf6b421-2a74-4556-9fa3-bb1098f07abd),
version(1.0)
]
interface service
{
    void inject_to_process([in] unsigned int pid, [in] unsigned long long envFlag);
	
	inline const unsigned int MAX_PIDS = 1024;
	void get_all_process_id_in_env([in] unsigned long long envFlag,
		[out, length_is(*count), size_is(MAX_PIDS)] unsigned long long pids[],
		[out] unsigned int* count);
}
